"""cognitive core tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-13 11:15:45.335938
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cog_agent",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("default_authority", sa.Integer(), nullable=False),
        sa.Column("tools", sa.JSON(), nullable=False),
        sa.Column("memory_access", sa.JSON(), nullable=False),
        sa.Column("goal_ids", sa.JSON(), nullable=False),
        sa.Column("policy_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_agent")),
    )
    op.create_index(op.f("ix_cog_agent_name"), "cog_agent", ["name"], unique=False)
    op.create_index(op.f("ix_cog_agent_role"), "cog_agent", ["role"], unique=False)
    op.create_index(op.f("ix_cog_agent_status"), "cog_agent", ["status"], unique=False)
    op.create_index(op.f("ix_cog_agent_tenant_id"), "cog_agent", ["tenant_id"], unique=False)
    op.create_table(
        "cog_episodic_event",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("conversation", sa.Uuid(), nullable=True),
        sa.Column("customer", sa.Uuid(), nullable=True),
        sa.Column("project", sa.Uuid(), nullable=True),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("related_entities", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_episodic_event")),
    )
    op.create_index(
        op.f("ix_cog_episodic_event_actor"), "cog_episodic_event", ["actor"], unique=False
    )
    op.create_index(
        op.f("ix_cog_episodic_event_conversation"),
        "cog_episodic_event",
        ["conversation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cog_episodic_event_customer"), "cog_episodic_event", ["customer"], unique=False
    )
    op.create_index(
        op.f("ix_cog_episodic_event_occurred_at"),
        "cog_episodic_event",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cog_episodic_event_project"), "cog_episodic_event", ["project"], unique=False
    )
    op.create_index(
        op.f("ix_cog_episodic_event_tenant_id"), "cog_episodic_event", ["tenant_id"], unique=False
    )
    op.create_table(
        "cog_event",
        sa.Column("type", sa.String(length=120), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.Column("causation_id", sa.Uuid(), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_event")),
    )
    op.create_index(op.f("ix_cog_event_aggregate_id"), "cog_event", ["aggregate_id"], unique=False)
    op.create_index(
        op.f("ix_cog_event_correlation_id"), "cog_event", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_cog_event_occurred_at"), "cog_event", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_cog_event_tenant_id"), "cog_event", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_cog_event_type"), "cog_event", ["type"], unique=False)
    op.create_table(
        "cog_goal",
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("owner_agent_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("depends_on", sa.JSON(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_goal")),
    )
    op.create_index(op.f("ix_cog_goal_level"), "cog_goal", ["level"], unique=False)
    op.create_index(
        op.f("ix_cog_goal_owner_agent_id"), "cog_goal", ["owner_agent_id"], unique=False
    )
    op.create_index(op.f("ix_cog_goal_parent_id"), "cog_goal", ["parent_id"], unique=False)
    op.create_index(op.f("ix_cog_goal_status"), "cog_goal", ["status"], unique=False)
    op.create_index(op.f("ix_cog_goal_tenant_id"), "cog_goal", ["tenant_id"], unique=False)
    op.create_table(
        "cog_goal_history",
        sa.Column("goal_id", sa.Uuid(), nullable=False),
        sa.Column("change", sa.String(length=500), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_goal_history")),
    )
    op.create_index(
        op.f("ix_cog_goal_history_goal_id"), "cog_goal_history", ["goal_id"], unique=False
    )
    op.create_index(
        op.f("ix_cog_goal_history_tenant_id"), "cog_goal_history", ["tenant_id"], unique=False
    )
    op.create_table(
        "cog_memory_item",
        sa.Column("owner_agent_id", sa.Uuid(), nullable=True),
        sa.Column("memory_type", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column("source_event_id", sa.Uuid(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("related_entity_ids", sa.JSON(), nullable=False),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column(
            "last_accessed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_memory_item")),
    )
    op.create_index(
        op.f("ix_cog_memory_item_archived"), "cog_memory_item", ["archived"], unique=False
    )
    op.create_index(
        op.f("ix_cog_memory_item_memory_type"), "cog_memory_item", ["memory_type"], unique=False
    )
    op.create_index(
        op.f("ix_cog_memory_item_owner_agent_id"),
        "cog_memory_item",
        ["owner_agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cog_memory_item_tenant_id"), "cog_memory_item", ["tenant_id"], unique=False
    )
    op.create_table(
        "cog_plan",
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("tasks", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_plan")),
    )
    op.create_index(op.f("ix_cog_plan_agent_id"), "cog_plan", ["agent_id"], unique=False)
    op.create_index(op.f("ix_cog_plan_goal_id"), "cog_plan", ["goal_id"], unique=False)
    op.create_index(op.f("ix_cog_plan_status"), "cog_plan", ["status"], unique=False)
    op.create_index(op.f("ix_cog_plan_tenant_id"), "cog_plan", ["tenant_id"], unique=False)
    op.create_table(
        "cog_policy",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=200), nullable=False),
        sa.Column("resource", sa.String(length=200), nullable=False),
        sa.Column("effect", sa.String(length=20), nullable=False),
        sa.Column("min_authority", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_policy")),
    )
    op.create_index(op.f("ix_cog_policy_action"), "cog_policy", ["action"], unique=False)
    op.create_index(op.f("ix_cog_policy_enabled"), "cog_policy", ["enabled"], unique=False)
    op.create_index(op.f("ix_cog_policy_priority"), "cog_policy", ["priority"], unique=False)
    op.create_index(op.f("ix_cog_policy_tenant_id"), "cog_policy", ["tenant_id"], unique=False)
    op.create_table(
        "cog_procedure",
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_procedure")),
    )
    op.create_index(op.f("ix_cog_procedure_slug"), "cog_procedure", ["slug"], unique=False)
    op.create_index(
        op.f("ix_cog_procedure_tenant_id"), "cog_procedure", ["tenant_id"], unique=False
    )
    op.create_table(
        "cog_reflection",
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("lessons_learned", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("future_recommendations", sa.JSON(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_reflection")),
    )
    op.create_index(
        op.f("ix_cog_reflection_agent_id"), "cog_reflection", ["agent_id"], unique=False
    )
    op.create_index(op.f("ix_cog_reflection_success"), "cog_reflection", ["success"], unique=False)
    op.create_index(op.f("ix_cog_reflection_task_id"), "cog_reflection", ["task_id"], unique=False)
    op.create_index(
        op.f("ix_cog_reflection_tenant_id"), "cog_reflection", ["tenant_id"], unique=False
    )
    op.create_table(
        "cog_relationship",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("relation", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_relationship")),
    )
    op.create_index(
        op.f("ix_cog_relationship_relation"), "cog_relationship", ["relation"], unique=False
    )
    op.create_index(
        op.f("ix_cog_relationship_source_id"), "cog_relationship", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_cog_relationship_target_id"), "cog_relationship", ["target_id"], unique=False
    )
    op.create_index(
        op.f("ix_cog_relationship_tenant_id"), "cog_relationship", ["tenant_id"], unique=False
    )
    op.create_table(
        "cog_semantic_item",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("superseded_by", sa.Uuid(), nullable=True),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_semantic_item")),
    )
    op.create_index(op.f("ix_cog_semantic_item_kind"), "cog_semantic_item", ["kind"], unique=False)
    op.create_index(op.f("ix_cog_semantic_item_name"), "cog_semantic_item", ["name"], unique=False)
    op.create_index(
        op.f("ix_cog_semantic_item_tenant_id"), "cog_semantic_item", ["tenant_id"], unique=False
    )
    op.create_table(
        "cog_tool",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("input_schema", sa.JSON(), nullable=False),
        sa.Column("output_schema", sa.JSON(), nullable=False),
        sa.Column("side_effect", sa.String(length=20), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("health", sa.String(length=20), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_tool")),
    )
    op.create_index(op.f("ix_cog_tool_name"), "cog_tool", ["name"], unique=False)
    op.create_index(op.f("ix_cog_tool_tenant_id"), "cog_tool", ["tenant_id"], unique=False)
    op.create_table(
        "cog_working_entry",
        sa.Column("scope_key", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_estimate", sa.Integer(), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cog_working_entry")),
    )
    op.create_index(
        op.f("ix_cog_working_entry_expires_at"), "cog_working_entry", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_cog_working_entry_scope_key"), "cog_working_entry", ["scope_key"], unique=False
    )
    op.create_index(
        op.f("ix_cog_working_entry_tenant_id"), "cog_working_entry", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cog_working_entry_tenant_id"), table_name="cog_working_entry")
    op.drop_index(op.f("ix_cog_working_entry_scope_key"), table_name="cog_working_entry")
    op.drop_index(op.f("ix_cog_working_entry_expires_at"), table_name="cog_working_entry")
    op.drop_table("cog_working_entry")
    op.drop_index(op.f("ix_cog_tool_tenant_id"), table_name="cog_tool")
    op.drop_index(op.f("ix_cog_tool_name"), table_name="cog_tool")
    op.drop_table("cog_tool")
    op.drop_index(op.f("ix_cog_semantic_item_tenant_id"), table_name="cog_semantic_item")
    op.drop_index(op.f("ix_cog_semantic_item_name"), table_name="cog_semantic_item")
    op.drop_index(op.f("ix_cog_semantic_item_kind"), table_name="cog_semantic_item")
    op.drop_table("cog_semantic_item")
    op.drop_index(op.f("ix_cog_relationship_tenant_id"), table_name="cog_relationship")
    op.drop_index(op.f("ix_cog_relationship_target_id"), table_name="cog_relationship")
    op.drop_index(op.f("ix_cog_relationship_source_id"), table_name="cog_relationship")
    op.drop_index(op.f("ix_cog_relationship_relation"), table_name="cog_relationship")
    op.drop_table("cog_relationship")
    op.drop_index(op.f("ix_cog_reflection_tenant_id"), table_name="cog_reflection")
    op.drop_index(op.f("ix_cog_reflection_task_id"), table_name="cog_reflection")
    op.drop_index(op.f("ix_cog_reflection_success"), table_name="cog_reflection")
    op.drop_index(op.f("ix_cog_reflection_agent_id"), table_name="cog_reflection")
    op.drop_table("cog_reflection")
    op.drop_index(op.f("ix_cog_procedure_tenant_id"), table_name="cog_procedure")
    op.drop_index(op.f("ix_cog_procedure_slug"), table_name="cog_procedure")
    op.drop_table("cog_procedure")
    op.drop_index(op.f("ix_cog_policy_tenant_id"), table_name="cog_policy")
    op.drop_index(op.f("ix_cog_policy_priority"), table_name="cog_policy")
    op.drop_index(op.f("ix_cog_policy_enabled"), table_name="cog_policy")
    op.drop_index(op.f("ix_cog_policy_action"), table_name="cog_policy")
    op.drop_table("cog_policy")
    op.drop_index(op.f("ix_cog_plan_tenant_id"), table_name="cog_plan")
    op.drop_index(op.f("ix_cog_plan_status"), table_name="cog_plan")
    op.drop_index(op.f("ix_cog_plan_goal_id"), table_name="cog_plan")
    op.drop_index(op.f("ix_cog_plan_agent_id"), table_name="cog_plan")
    op.drop_table("cog_plan")
    op.drop_index(op.f("ix_cog_memory_item_tenant_id"), table_name="cog_memory_item")
    op.drop_index(op.f("ix_cog_memory_item_owner_agent_id"), table_name="cog_memory_item")
    op.drop_index(op.f("ix_cog_memory_item_memory_type"), table_name="cog_memory_item")
    op.drop_index(op.f("ix_cog_memory_item_archived"), table_name="cog_memory_item")
    op.drop_table("cog_memory_item")
    op.drop_index(op.f("ix_cog_goal_history_tenant_id"), table_name="cog_goal_history")
    op.drop_index(op.f("ix_cog_goal_history_goal_id"), table_name="cog_goal_history")
    op.drop_table("cog_goal_history")
    op.drop_index(op.f("ix_cog_goal_tenant_id"), table_name="cog_goal")
    op.drop_index(op.f("ix_cog_goal_status"), table_name="cog_goal")
    op.drop_index(op.f("ix_cog_goal_parent_id"), table_name="cog_goal")
    op.drop_index(op.f("ix_cog_goal_owner_agent_id"), table_name="cog_goal")
    op.drop_index(op.f("ix_cog_goal_level"), table_name="cog_goal")
    op.drop_table("cog_goal")
    op.drop_index(op.f("ix_cog_event_type"), table_name="cog_event")
    op.drop_index(op.f("ix_cog_event_tenant_id"), table_name="cog_event")
    op.drop_index(op.f("ix_cog_event_occurred_at"), table_name="cog_event")
    op.drop_index(op.f("ix_cog_event_correlation_id"), table_name="cog_event")
    op.drop_index(op.f("ix_cog_event_aggregate_id"), table_name="cog_event")
    op.drop_table("cog_event")
    op.drop_index(op.f("ix_cog_episodic_event_tenant_id"), table_name="cog_episodic_event")
    op.drop_index(op.f("ix_cog_episodic_event_project"), table_name="cog_episodic_event")
    op.drop_index(op.f("ix_cog_episodic_event_occurred_at"), table_name="cog_episodic_event")
    op.drop_index(op.f("ix_cog_episodic_event_customer"), table_name="cog_episodic_event")
    op.drop_index(op.f("ix_cog_episodic_event_conversation"), table_name="cog_episodic_event")
    op.drop_index(op.f("ix_cog_episodic_event_actor"), table_name="cog_episodic_event")
    op.drop_table("cog_episodic_event")
    op.drop_index(op.f("ix_cog_agent_tenant_id"), table_name="cog_agent")
    op.drop_index(op.f("ix_cog_agent_status"), table_name="cog_agent")
    op.drop_index(op.f("ix_cog_agent_role"), table_name="cog_agent")
    op.drop_index(op.f("ix_cog_agent_name"), table_name="cog_agent")
    op.drop_table("cog_agent")
    # ### end Alembic commands ###
