"""program manager tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-13 16:21:25.126845
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pm_contact",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("relationship_score", sa.Float(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_contact")),
    )
    op.create_index(op.f("ix_pm_contact_email"), "pm_contact", ["email"], unique=False)
    op.create_index(
        op.f("ix_pm_contact_organization_id"), "pm_contact", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_pm_contact_tenant_id"), "pm_contact", ["tenant_id"], unique=False)
    op.create_table(
        "pm_crm_task",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("opportunity_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("owner_agent_id", sa.Uuid(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_crm_task")),
    )
    op.create_index(op.f("ix_pm_crm_task_due_at"), "pm_crm_task", ["due_at"], unique=False)
    op.create_index(
        op.f("ix_pm_crm_task_opportunity_id"), "pm_crm_task", ["opportunity_id"], unique=False
    )
    op.create_index(
        op.f("ix_pm_crm_task_organization_id"), "pm_crm_task", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_pm_crm_task_owner_agent_id"), "pm_crm_task", ["owner_agent_id"], unique=False
    )
    op.create_index(op.f("ix_pm_crm_task_project_id"), "pm_crm_task", ["project_id"], unique=False)
    op.create_index(op.f("ix_pm_crm_task_status"), "pm_crm_task", ["status"], unique=False)
    op.create_index(op.f("ix_pm_crm_task_tenant_id"), "pm_crm_task", ["tenant_id"], unique=False)
    op.create_table(
        "pm_lead",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("owner_agent_id", sa.Uuid(), nullable=True),
        sa.Column("opportunity_id", sa.Uuid(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_lead")),
    )
    op.create_index(op.f("ix_pm_lead_contact_id"), "pm_lead", ["contact_id"], unique=False)
    op.create_index(op.f("ix_pm_lead_opportunity_id"), "pm_lead", ["opportunity_id"], unique=False)
    op.create_index(
        op.f("ix_pm_lead_organization_id"), "pm_lead", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_pm_lead_owner_agent_id"), "pm_lead", ["owner_agent_id"], unique=False)
    op.create_index(op.f("ix_pm_lead_source"), "pm_lead", ["source"], unique=False)
    op.create_index(op.f("ix_pm_lead_status"), "pm_lead", ["status"], unique=False)
    op.create_index(op.f("ix_pm_lead_tenant_id"), "pm_lead", ["tenant_id"], unique=False)
    op.create_table(
        "pm_meeting",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("contact_ids", sa.JSON(), nullable=False),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("agenda", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_meeting")),
    )
    op.create_index(
        op.f("ix_pm_meeting_opportunity_id"), "pm_meeting", ["opportunity_id"], unique=False
    )
    op.create_index(
        op.f("ix_pm_meeting_organization_id"), "pm_meeting", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_pm_meeting_scheduled_at"), "pm_meeting", ["scheduled_at"], unique=False
    )
    op.create_index(op.f("ix_pm_meeting_status"), "pm_meeting", ["status"], unique=False)
    op.create_index(op.f("ix_pm_meeting_tenant_id"), "pm_meeting", ["tenant_id"], unique=False)
    op.create_table(
        "pm_note",
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("opportunity_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_note")),
    )
    op.create_index(op.f("ix_pm_note_author"), "pm_note", ["author"], unique=False)
    op.create_index(op.f("ix_pm_note_contact_id"), "pm_note", ["contact_id"], unique=False)
    op.create_index(op.f("ix_pm_note_opportunity_id"), "pm_note", ["opportunity_id"], unique=False)
    op.create_index(
        op.f("ix_pm_note_organization_id"), "pm_note", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_pm_note_project_id"), "pm_note", ["project_id"], unique=False)
    op.create_index(op.f("ix_pm_note_tenant_id"), "pm_note", ["tenant_id"], unique=False)
    op.create_table(
        "pm_opportunity",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("expected_close_date", sa.Date(), nullable=True),
        sa.Column("primary_contact_id", sa.Uuid(), nullable=True),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("owner_agent_id", sa.Uuid(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_opportunity")),
    )
    op.create_index(op.f("ix_pm_opportunity_lead_id"), "pm_opportunity", ["lead_id"], unique=False)
    op.create_index(
        op.f("ix_pm_opportunity_organization_id"),
        "pm_opportunity",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pm_opportunity_owner_agent_id"), "pm_opportunity", ["owner_agent_id"], unique=False
    )
    op.create_index(op.f("ix_pm_opportunity_stage"), "pm_opportunity", ["stage"], unique=False)
    op.create_index(
        op.f("ix_pm_opportunity_tenant_id"), "pm_opportunity", ["tenant_id"], unique=False
    )
    op.create_table(
        "pm_organization",
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("industry", sa.String(length=255), nullable=True),
        sa.Column("size", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("relationship_score", sa.Float(), nullable=False),
        sa.Column("trust_score", sa.Float(), nullable=False),
        sa.Column("importance_score", sa.Float(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_organization")),
    )
    op.create_index(op.f("ix_pm_organization_domain"), "pm_organization", ["domain"], unique=False)
    op.create_index(op.f("ix_pm_organization_name"), "pm_organization", ["name"], unique=False)
    op.create_index(op.f("ix_pm_organization_status"), "pm_organization", ["status"], unique=False)
    op.create_index(
        op.f("ix_pm_organization_tenant_id"), "pm_organization", ["tenant_id"], unique=False
    )
    op.create_table(
        "pm_plan",
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("goal_type", sa.String(length=30), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_plan")),
    )
    op.create_index(op.f("ix_pm_plan_goal_id"), "pm_plan", ["goal_id"], unique=False)
    op.create_index(op.f("ix_pm_plan_run_id"), "pm_plan", ["run_id"], unique=False)
    op.create_index(op.f("ix_pm_plan_status"), "pm_plan", ["status"], unique=False)
    op.create_index(op.f("ix_pm_plan_tenant_id"), "pm_plan", ["tenant_id"], unique=False)
    op.create_table(
        "pm_project",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("health", sa.String(length=20), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("target_end_date", sa.Date(), nullable=True),
        sa.Column("owner_agent_id", sa.Uuid(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_project")),
    )
    op.create_index(
        op.f("ix_pm_project_opportunity_id"), "pm_project", ["opportunity_id"], unique=False
    )
    op.create_index(
        op.f("ix_pm_project_organization_id"), "pm_project", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_pm_project_owner_agent_id"), "pm_project", ["owner_agent_id"], unique=False
    )
    op.create_index(op.f("ix_pm_project_status"), "pm_project", ["status"], unique=False)
    op.create_index(op.f("ix_pm_project_tenant_id"), "pm_project", ["tenant_id"], unique=False)
    op.create_table(
        "pm_proposal",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sections", sa.JSON(), nullable=False),
        sa.Column("total_value", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("owner_agent_id", sa.Uuid(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_proposal")),
    )
    op.create_index(
        op.f("ix_pm_proposal_opportunity_id"), "pm_proposal", ["opportunity_id"], unique=False
    )
    op.create_index(
        op.f("ix_pm_proposal_organization_id"), "pm_proposal", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_pm_proposal_owner_agent_id"), "pm_proposal", ["owner_agent_id"], unique=False
    )
    op.create_index(op.f("ix_pm_proposal_status"), "pm_proposal", ["status"], unique=False)
    op.create_index(op.f("ix_pm_proposal_tenant_id"), "pm_proposal", ["tenant_id"], unique=False)
    op.create_table(
        "pm_run",
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("trigger_ref", sa.Uuid(), nullable=True),
        sa.Column("input_summary", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("goal_type", sa.String(length=30), nullable=True),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("states_visited", sa.JSON(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("awaiting_approval", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_run")),
    )
    op.create_index(op.f("ix_pm_run_agent_id"), "pm_run", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_pm_run_awaiting_approval"), "pm_run", ["awaiting_approval"], unique=False
    )
    op.create_index(op.f("ix_pm_run_goal_id"), "pm_run", ["goal_id"], unique=False)
    op.create_index(op.f("ix_pm_run_organization_id"), "pm_run", ["organization_id"], unique=False)
    op.create_index(op.f("ix_pm_run_plan_id"), "pm_run", ["plan_id"], unique=False)
    op.create_index(op.f("ix_pm_run_started_at"), "pm_run", ["started_at"], unique=False)
    op.create_index(op.f("ix_pm_run_state"), "pm_run", ["state"], unique=False)
    op.create_index(op.f("ix_pm_run_success"), "pm_run", ["success"], unique=False)
    op.create_index(op.f("ix_pm_run_tenant_id"), "pm_run", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_pm_run_trigger"), "pm_run", ["trigger"], unique=False)
    op.create_index(op.f("ix_pm_run_trigger_ref"), "pm_run", ["trigger_ref"], unique=False)
    op.create_table(
        "pm_scheduled_action",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("goal_type", sa.String(length=30), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("subject_type", sa.String(length=20), nullable=True),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("cadence", sa.String(length=20), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_by_agent_id", sa.Uuid(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_scheduled_action")),
    )
    op.create_index(
        op.f("ix_pm_scheduled_action_created_by_agent_id"),
        "pm_scheduled_action",
        ["created_by_agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pm_scheduled_action_kind"), "pm_scheduled_action", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_pm_scheduled_action_run_at"), "pm_scheduled_action", ["run_at"], unique=False
    )
    op.create_index(
        op.f("ix_pm_scheduled_action_status"), "pm_scheduled_action", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_pm_scheduled_action_subject_id"),
        "pm_scheduled_action",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pm_scheduled_action_tenant_id"), "pm_scheduled_action", ["tenant_id"], unique=False
    )
    op.create_table(
        "pm_task",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_key", sa.String(length=100), nullable=False),
        sa.Column("goal_type", sa.String(length=30), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("authority_required", sa.Integer(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pm_task")),
    )
    op.create_index(
        op.f("ix_pm_task_requires_approval"), "pm_task", ["requires_approval"], unique=False
    )
    op.create_index(op.f("ix_pm_task_run_id"), "pm_task", ["run_id"], unique=False)
    op.create_index(op.f("ix_pm_task_status"), "pm_task", ["status"], unique=False)
    op.create_index(op.f("ix_pm_task_tenant_id"), "pm_task", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pm_task_tenant_id"), table_name="pm_task")
    op.drop_index(op.f("ix_pm_task_status"), table_name="pm_task")
    op.drop_index(op.f("ix_pm_task_run_id"), table_name="pm_task")
    op.drop_index(op.f("ix_pm_task_requires_approval"), table_name="pm_task")
    op.drop_table("pm_task")
    op.drop_index(op.f("ix_pm_scheduled_action_tenant_id"), table_name="pm_scheduled_action")
    op.drop_index(op.f("ix_pm_scheduled_action_subject_id"), table_name="pm_scheduled_action")
    op.drop_index(op.f("ix_pm_scheduled_action_status"), table_name="pm_scheduled_action")
    op.drop_index(op.f("ix_pm_scheduled_action_run_at"), table_name="pm_scheduled_action")
    op.drop_index(op.f("ix_pm_scheduled_action_kind"), table_name="pm_scheduled_action")
    op.drop_index(
        op.f("ix_pm_scheduled_action_created_by_agent_id"), table_name="pm_scheduled_action"
    )
    op.drop_table("pm_scheduled_action")
    op.drop_index(op.f("ix_pm_run_trigger_ref"), table_name="pm_run")
    op.drop_index(op.f("ix_pm_run_trigger"), table_name="pm_run")
    op.drop_index(op.f("ix_pm_run_tenant_id"), table_name="pm_run")
    op.drop_index(op.f("ix_pm_run_success"), table_name="pm_run")
    op.drop_index(op.f("ix_pm_run_state"), table_name="pm_run")
    op.drop_index(op.f("ix_pm_run_started_at"), table_name="pm_run")
    op.drop_index(op.f("ix_pm_run_plan_id"), table_name="pm_run")
    op.drop_index(op.f("ix_pm_run_organization_id"), table_name="pm_run")
    op.drop_index(op.f("ix_pm_run_goal_id"), table_name="pm_run")
    op.drop_index(op.f("ix_pm_run_awaiting_approval"), table_name="pm_run")
    op.drop_index(op.f("ix_pm_run_agent_id"), table_name="pm_run")
    op.drop_table("pm_run")
    op.drop_index(op.f("ix_pm_proposal_tenant_id"), table_name="pm_proposal")
    op.drop_index(op.f("ix_pm_proposal_status"), table_name="pm_proposal")
    op.drop_index(op.f("ix_pm_proposal_owner_agent_id"), table_name="pm_proposal")
    op.drop_index(op.f("ix_pm_proposal_organization_id"), table_name="pm_proposal")
    op.drop_index(op.f("ix_pm_proposal_opportunity_id"), table_name="pm_proposal")
    op.drop_table("pm_proposal")
    op.drop_index(op.f("ix_pm_project_tenant_id"), table_name="pm_project")
    op.drop_index(op.f("ix_pm_project_status"), table_name="pm_project")
    op.drop_index(op.f("ix_pm_project_owner_agent_id"), table_name="pm_project")
    op.drop_index(op.f("ix_pm_project_organization_id"), table_name="pm_project")
    op.drop_index(op.f("ix_pm_project_opportunity_id"), table_name="pm_project")
    op.drop_table("pm_project")
    op.drop_index(op.f("ix_pm_plan_tenant_id"), table_name="pm_plan")
    op.drop_index(op.f("ix_pm_plan_status"), table_name="pm_plan")
    op.drop_index(op.f("ix_pm_plan_run_id"), table_name="pm_plan")
    op.drop_index(op.f("ix_pm_plan_goal_id"), table_name="pm_plan")
    op.drop_table("pm_plan")
    op.drop_index(op.f("ix_pm_organization_tenant_id"), table_name="pm_organization")
    op.drop_index(op.f("ix_pm_organization_status"), table_name="pm_organization")
    op.drop_index(op.f("ix_pm_organization_name"), table_name="pm_organization")
    op.drop_index(op.f("ix_pm_organization_domain"), table_name="pm_organization")
    op.drop_table("pm_organization")
    op.drop_index(op.f("ix_pm_opportunity_tenant_id"), table_name="pm_opportunity")
    op.drop_index(op.f("ix_pm_opportunity_stage"), table_name="pm_opportunity")
    op.drop_index(op.f("ix_pm_opportunity_owner_agent_id"), table_name="pm_opportunity")
    op.drop_index(op.f("ix_pm_opportunity_organization_id"), table_name="pm_opportunity")
    op.drop_index(op.f("ix_pm_opportunity_lead_id"), table_name="pm_opportunity")
    op.drop_table("pm_opportunity")
    op.drop_index(op.f("ix_pm_note_tenant_id"), table_name="pm_note")
    op.drop_index(op.f("ix_pm_note_project_id"), table_name="pm_note")
    op.drop_index(op.f("ix_pm_note_organization_id"), table_name="pm_note")
    op.drop_index(op.f("ix_pm_note_opportunity_id"), table_name="pm_note")
    op.drop_index(op.f("ix_pm_note_contact_id"), table_name="pm_note")
    op.drop_index(op.f("ix_pm_note_author"), table_name="pm_note")
    op.drop_table("pm_note")
    op.drop_index(op.f("ix_pm_meeting_tenant_id"), table_name="pm_meeting")
    op.drop_index(op.f("ix_pm_meeting_status"), table_name="pm_meeting")
    op.drop_index(op.f("ix_pm_meeting_scheduled_at"), table_name="pm_meeting")
    op.drop_index(op.f("ix_pm_meeting_organization_id"), table_name="pm_meeting")
    op.drop_index(op.f("ix_pm_meeting_opportunity_id"), table_name="pm_meeting")
    op.drop_table("pm_meeting")
    op.drop_index(op.f("ix_pm_lead_tenant_id"), table_name="pm_lead")
    op.drop_index(op.f("ix_pm_lead_status"), table_name="pm_lead")
    op.drop_index(op.f("ix_pm_lead_source"), table_name="pm_lead")
    op.drop_index(op.f("ix_pm_lead_owner_agent_id"), table_name="pm_lead")
    op.drop_index(op.f("ix_pm_lead_organization_id"), table_name="pm_lead")
    op.drop_index(op.f("ix_pm_lead_opportunity_id"), table_name="pm_lead")
    op.drop_index(op.f("ix_pm_lead_contact_id"), table_name="pm_lead")
    op.drop_table("pm_lead")
    op.drop_index(op.f("ix_pm_crm_task_tenant_id"), table_name="pm_crm_task")
    op.drop_index(op.f("ix_pm_crm_task_status"), table_name="pm_crm_task")
    op.drop_index(op.f("ix_pm_crm_task_project_id"), table_name="pm_crm_task")
    op.drop_index(op.f("ix_pm_crm_task_owner_agent_id"), table_name="pm_crm_task")
    op.drop_index(op.f("ix_pm_crm_task_organization_id"), table_name="pm_crm_task")
    op.drop_index(op.f("ix_pm_crm_task_opportunity_id"), table_name="pm_crm_task")
    op.drop_index(op.f("ix_pm_crm_task_due_at"), table_name="pm_crm_task")
    op.drop_table("pm_crm_task")
    op.drop_index(op.f("ix_pm_contact_tenant_id"), table_name="pm_contact")
    op.drop_index(op.f("ix_pm_contact_organization_id"), table_name="pm_contact")
    op.drop_index(op.f("ix_pm_contact_email"), table_name="pm_contact")
    op.drop_table("pm_contact")
    # ### end Alembic commands ###
