"""workspace integration tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-13 19:48:38.394415
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ws_approval_policy",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("communication_type", sa.String(length=30), nullable=True),
        sa.Column("customer_organization_id", sa.Uuid(), nullable=True),
        sa.Column("customer_contact_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("min_authority", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ws_approval_policy")),
    )
    op.create_index(
        op.f("ix_ws_approval_policy_agent_id"), "ws_approval_policy", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_ws_approval_policy_customer_organization_id"),
        "ws_approval_policy",
        ["customer_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ws_approval_policy_enabled"), "ws_approval_policy", ["enabled"], unique=False
    )
    op.create_index(
        op.f("ix_ws_approval_policy_priority"), "ws_approval_policy", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_ws_approval_policy_tenant_id"), "ws_approval_policy", ["tenant_id"], unique=False
    )
    op.create_table(
        "ws_approval_request",
        sa.Column("communication_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("customer_organization_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("decided_by", sa.String(length=255), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ws_approval_request")),
    )
    op.create_index(
        op.f("ix_ws_approval_request_customer_organization_id"),
        "ws_approval_request",
        ["customer_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ws_approval_request_status"), "ws_approval_request", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ws_approval_request_tenant_id"), "ws_approval_request", ["tenant_id"], unique=False
    )
    op.create_table(
        "ws_audit_log",
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("resource", sa.String(length=500), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ws_audit_log")),
    )
    op.create_index(op.f("ix_ws_audit_log_action"), "ws_audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_ws_audit_log_tenant_id"), "ws_audit_log", ["tenant_id"], unique=False)
    op.create_table(
        "ws_connection",
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("mailbox", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ws_connection")),
    )
    op.create_index(op.f("ix_ws_connection_mailbox"), "ws_connection", ["mailbox"], unique=False)
    op.create_index(
        op.f("ix_ws_connection_tenant_id"), "ws_connection", ["tenant_id"], unique=False
    )
    op.create_table(
        "ws_credential",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("provider_tenant_id", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("client_secret_encrypted", sa.Text(), nullable=False),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=True),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ws_credential")),
    )
    op.create_index(
        op.f("ix_ws_credential_connection_id"), "ws_credential", ["connection_id"], unique=False
    )
    op.create_index(
        op.f("ix_ws_credential_tenant_id"), "ws_credential", ["tenant_id"], unique=False
    )
    op.create_table(
        "ws_dead_letter",
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ws_dead_letter")),
    )
    op.create_index(op.f("ix_ws_dead_letter_kind"), "ws_dead_letter", ["kind"], unique=False)
    op.create_index(
        op.f("ix_ws_dead_letter_tenant_id"), "ws_dead_letter", ["tenant_id"], unique=False
    )
    op.create_table(
        "ws_index_entry",
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("source_provider_id", sa.String(length=512), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("web_url", sa.String(length=1000), nullable=True),
        sa.Column("embedding", sa.JSON(), nullable=False),
        sa.Column("ref", sa.JSON(), nullable=False),
        sa.Column(
            "indexed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ws_index_entry")),
    )
    op.create_index(
        op.f("ix_ws_index_entry_indexed_at"), "ws_index_entry", ["indexed_at"], unique=False
    )
    op.create_index(op.f("ix_ws_index_entry_kind"), "ws_index_entry", ["kind"], unique=False)
    op.create_index(
        op.f("ix_ws_index_entry_source_provider_id"),
        "ws_index_entry",
        ["source_provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ws_index_entry_tenant_id"), "ws_index_entry", ["tenant_id"], unique=False
    )
    op.create_table(
        "ws_message",
        sa.Column("connection_id", sa.Uuid(), nullable=True),
        sa.Column("provider_id", sa.String(length=512), nullable=False),
        sa.Column("conversation_id", sa.String(length=512), nullable=True),
        sa.Column("internet_message_id", sa.String(length=512), nullable=True),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body_preview", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_html", sa.Boolean(), nullable=False),
        sa.Column("sender_address", sa.String(length=320), nullable=False),
        sa.Column("sender_name", sa.String(length=255), nullable=False),
        sa.Column("recipients_to", sa.JSON(), nullable=False),
        sa.Column("recipients_cc", sa.JSON(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_flagged", sa.Boolean(), nullable=False),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("folder", sa.String(length=255), nullable=False),
        sa.Column("has_attachments", sa.Boolean(), nullable=False),
        sa.Column("attachments", sa.JSON(), nullable=False),
        sa.Column("customer_organization_id", sa.Uuid(), nullable=True),
        sa.Column("customer_contact_id", sa.Uuid(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ws_message")),
    )
    op.create_index(
        op.f("ix_ws_message_connection_id"), "ws_message", ["connection_id"], unique=False
    )
    op.create_index(
        op.f("ix_ws_message_conversation_id"), "ws_message", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("ix_ws_message_customer_organization_id"),
        "ws_message",
        ["customer_organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_ws_message_folder"), "ws_message", ["folder"], unique=False)
    op.create_index(op.f("ix_ws_message_provider_id"), "ws_message", ["provider_id"], unique=False)
    op.create_index(op.f("ix_ws_message_received_at"), "ws_message", ["received_at"], unique=False)
    op.create_index(op.f("ix_ws_message_tenant_id"), "ws_message", ["tenant_id"], unique=False)
    op.create_table(
        "ws_sync_job",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("resource", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("items_processed", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ws_sync_job")),
    )
    op.create_index(
        op.f("ix_ws_sync_job_connection_id"), "ws_sync_job", ["connection_id"], unique=False
    )
    op.create_index(op.f("ix_ws_sync_job_started_at"), "ws_sync_job", ["started_at"], unique=False)
    op.create_index(op.f("ix_ws_sync_job_tenant_id"), "ws_sync_job", ["tenant_id"], unique=False)
    op.create_table(
        "ws_sync_state",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("resource", sa.String(length=30), nullable=False),
        sa.Column("delta_token", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("items_synced", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ws_sync_state")),
    )
    op.create_index(
        op.f("ix_ws_sync_state_connection_id"), "ws_sync_state", ["connection_id"], unique=False
    )
    op.create_index(op.f("ix_ws_sync_state_resource"), "ws_sync_state", ["resource"], unique=False)
    op.create_index(
        op.f("ix_ws_sync_state_tenant_id"), "ws_sync_state", ["tenant_id"], unique=False
    )
    op.create_table(
        "ws_webhook_subscription",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("resource", sa.String(length=500), nullable=False),
        sa.Column("change_types", sa.JSON(), nullable=False),
        sa.Column("notification_url", sa.String(length=1000), nullable=False),
        sa.Column("client_state", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ws_webhook_subscription")),
    )
    op.create_index(
        op.f("ix_ws_webhook_subscription_connection_id"),
        "ws_webhook_subscription",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ws_webhook_subscription_expires_at"),
        "ws_webhook_subscription",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ws_webhook_subscription_provider_subscription_id"),
        "ws_webhook_subscription",
        ["provider_subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ws_webhook_subscription_tenant_id"),
        "ws_webhook_subscription",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ws_webhook_subscription_tenant_id"), table_name="ws_webhook_subscription"
    )
    op.drop_index(
        op.f("ix_ws_webhook_subscription_provider_subscription_id"),
        table_name="ws_webhook_subscription",
    )
    op.drop_index(
        op.f("ix_ws_webhook_subscription_expires_at"), table_name="ws_webhook_subscription"
    )
    op.drop_index(
        op.f("ix_ws_webhook_subscription_connection_id"), table_name="ws_webhook_subscription"
    )
    op.drop_table("ws_webhook_subscription")
    op.drop_index(op.f("ix_ws_sync_state_tenant_id"), table_name="ws_sync_state")
    op.drop_index(op.f("ix_ws_sync_state_resource"), table_name="ws_sync_state")
    op.drop_index(op.f("ix_ws_sync_state_connection_id"), table_name="ws_sync_state")
    op.drop_table("ws_sync_state")
    op.drop_index(op.f("ix_ws_sync_job_tenant_id"), table_name="ws_sync_job")
    op.drop_index(op.f("ix_ws_sync_job_started_at"), table_name="ws_sync_job")
    op.drop_index(op.f("ix_ws_sync_job_connection_id"), table_name="ws_sync_job")
    op.drop_table("ws_sync_job")
    op.drop_index(op.f("ix_ws_message_tenant_id"), table_name="ws_message")
    op.drop_index(op.f("ix_ws_message_received_at"), table_name="ws_message")
    op.drop_index(op.f("ix_ws_message_provider_id"), table_name="ws_message")
    op.drop_index(op.f("ix_ws_message_folder"), table_name="ws_message")
    op.drop_index(op.f("ix_ws_message_customer_organization_id"), table_name="ws_message")
    op.drop_index(op.f("ix_ws_message_conversation_id"), table_name="ws_message")
    op.drop_index(op.f("ix_ws_message_connection_id"), table_name="ws_message")
    op.drop_table("ws_message")
    op.drop_index(op.f("ix_ws_index_entry_tenant_id"), table_name="ws_index_entry")
    op.drop_index(op.f("ix_ws_index_entry_source_provider_id"), table_name="ws_index_entry")
    op.drop_index(op.f("ix_ws_index_entry_kind"), table_name="ws_index_entry")
    op.drop_index(op.f("ix_ws_index_entry_indexed_at"), table_name="ws_index_entry")
    op.drop_table("ws_index_entry")
    op.drop_index(op.f("ix_ws_dead_letter_tenant_id"), table_name="ws_dead_letter")
    op.drop_index(op.f("ix_ws_dead_letter_kind"), table_name="ws_dead_letter")
    op.drop_table("ws_dead_letter")
    op.drop_index(op.f("ix_ws_credential_tenant_id"), table_name="ws_credential")
    op.drop_index(op.f("ix_ws_credential_connection_id"), table_name="ws_credential")
    op.drop_table("ws_credential")
    op.drop_index(op.f("ix_ws_connection_tenant_id"), table_name="ws_connection")
    op.drop_index(op.f("ix_ws_connection_mailbox"), table_name="ws_connection")
    op.drop_table("ws_connection")
    op.drop_index(op.f("ix_ws_audit_log_tenant_id"), table_name="ws_audit_log")
    op.drop_index(op.f("ix_ws_audit_log_action"), table_name="ws_audit_log")
    op.drop_table("ws_audit_log")
    op.drop_index(op.f("ix_ws_approval_request_tenant_id"), table_name="ws_approval_request")
    op.drop_index(op.f("ix_ws_approval_request_status"), table_name="ws_approval_request")
    op.drop_index(
        op.f("ix_ws_approval_request_customer_organization_id"), table_name="ws_approval_request"
    )
    op.drop_table("ws_approval_request")
    op.drop_index(op.f("ix_ws_approval_policy_tenant_id"), table_name="ws_approval_policy")
    op.drop_index(op.f("ix_ws_approval_policy_priority"), table_name="ws_approval_policy")
    op.drop_index(op.f("ix_ws_approval_policy_enabled"), table_name="ws_approval_policy")
    op.drop_index(
        op.f("ix_ws_approval_policy_customer_organization_id"), table_name="ws_approval_policy"
    )
    op.drop_index(op.f("ix_ws_approval_policy_agent_id"), table_name="ws_approval_policy")
    op.drop_table("ws_approval_policy")
    # ### end Alembic commands ###
